#!/usr/bin/env bash

if [[ $# -lt 1 ]]; then
  echo wtf no files
  exit 1
fi

#find . -type f -print0 | xargs -0 fixup

# single-line no-args fatal
sed -i 's/fatal(\([a-zA-Z_][-a-zA-Z>_0-9]*\))/\1()/' $@

# single-line fatal with one or more args
sed -i 's/fatal(\([a-zA-Z_][-a-zA-Z>_0-9]*\), /\1(/' $@

sed -i 's/YFATAL(\([a-zA-Z_][-a-zA-Z>_0-9]*\), /\1(/' $@

# single-line enter followed by newline
perl -i -0pe 's/^\s*enter;\n\n//mg' $@

# single-line finally : coda and preceding empty line
perl -i -0pe 's/\n\n\s*finally : coda;//mg' $@

# delete includes
sed -i '/#include ".*errtab.h"/d' $@
sed -i '/#include "xapi/d' $@
sed -i '/#include "logger/d' $@
sed -i '/#include "logging.h"/d' $@

# replace xapi -> void
sed -i 's/xapi/void/' $@

sed -i 's/lenter; //' $@
sed -i 's/finally : lcoda; //' $@
