#!/usr/bin/perl

use strict;
use warnings;

my @S;	# strong
my @W;	# weak

while(<STDIN>)
{
	if(/^[^:]+:$/)	# -MP lines, only
	{
		my $line = substr $_, 0, -2;	# exclude trailing newline and colon

		if($line =~ /\.lex\.h$/)
		{
			push @S, $line;				# strong dependency on the header
			$line =~ s/\.lex\.h/.lex/;
			push @W, $line;				# weak dependency on the object
		}
		elsif($line =~ /\.tab\.h$/)
		{
			push @S, $line;				# strong dependency on the header
			$line =~ s/\.tab\.h/.tab/;
			push @W, $line;				# weak dependency on the object
		}
		else
		{
			push @S, $line;				# strong dependency on the header

			# corresponding .c file
			$line =~ s/\.h$/.c/;

			if(-f $line)
			{
				$line =~ s/\.c$//;
				push @W, $line;			# weak dependency on the object, if the c file exists
			}
		}
	}
}

#
# args come in pairs ; target, and extension to use for its object-file dependencies
#

for(my $x = 0; $x <= $#ARGV; $x += 2)
{
	if(@S)
	{
		print "[ $ARGV[$x] ] : [\n";
		print "$_\n" for @S;
		print "]\n";
	}

	if(@W)
	{
		print "[ $ARGV[$x] ] :* [\n";
		print "$_.$ARGV[$x+1]\n" for @W;
		print "]\n";
	}
}
