#!/usr/bin/perl

use strict;
use warnings;

my $lic = <<END;
/* Copyright (c) 2012-2013 Todd Freed <todd.freed\@gmail.com>

   This file is part of fab.
   
   fab is free software: you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation, either version 3 of the License, or
   (at your option) any later version.
   
   fab is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.
   
   You should have received a copy of the GNU General Public License
   along with fab.  If not, see <http://www.gnu.org/licenses/>. */

END

for (map { chomp; $_ } qx|find . -type f|)
{
	if(/\.c$/) { }
	elsif(/\.h$/) { }
	elsif(/\.l$/) { }
	elsif(/\.y$/) { }
	elsif(/\.fab$/) { }
	elsif(/\.sh$/) { }
	elsif(/fabfile$/) { }
	elsif(/gcc-dep/) { }
	else
	{
		print "SKIP - $_\n";
		next;
	}

	print "C - $_\n";

	my $fh;
	unless(open($fh, "<", $_))
	{
		die "could not open $_ : $!"
	}

	local $/ = undef;
	my $s = <$fh>;

	close $fh;
	unless(open($fh, ">", $_))
	{
		die "could not open $_ : $!"
	}

	if($s =~ /\/\* Copyright[^*]+\*\/\n+/)
	{
		print $fh "$lic", substr($s, $+[0]), "\n"
	}
	else
	{
		print $fh "$lic\n$s"
	}
}
