#!/usr/bin/env perl

use strict;
use warnings;
$SIG{__WARN__} = sub { die @_ };

use POSIX;
use File::Basename;
use Cwd;
our $repodir;
BEGIN { $repodir = dirname(Cwd::realpath("$0/..")) }
use lib "$repodir/integ/lib";
use util;
use tree;
use bam;

my $testdir = setup(<<'TREE');
|-- module.bam
TREE

# before
assert_stats(undef, {
    modules => 1
  , system_state_ok => 1
});

# create config file
open my $fh, ">", "$testdir/config.bam" or die $!;
print $fh <<'TEXT';
build : {
  concurrency : 42
}
TEXT
close $fh;

# after
reconcile();
assert_stats(undef, {
    modules => 1
  , system_state_ok => 2
});
assert_stats("config.bam", {
    parsed_try => 1
  , parsed => 1
  , state => "fresh"
});
