#!/usr/bin/env perl

use strict;
use warnings;
$SIG{__WARN__} = sub { die @_ };

use POSIX;
use File::Basename;
use Cwd;
our $repodir;
BEGIN { $repodir = dirname(Cwd::realpath("$0/..")) }
use lib "$repodir/integ/lib";
use util;
use tree;
use bam;

# module file - boats is created by separate rules which each reference the same formula
my $testdir = setup(<<'TREE');
|-- module.bam <<
rule -- boats : foo.bam
rule -- boats : foo.bam
rule boats -> //module/targets
>>
|-- foo.bam << 0777
#!/usr/bin/env perl
open FH, ">", $ENV{bm_target} or die $!;
print FH "foo\n";
close FH;
>>
TREE

# before
assert_stats(undef, {
    modules => 1
  , system_state_ok => 0
});
assert_stats(".", {
    reloaded => 1
});
assert_stats("module.bam", {
    parsed_try => 1
  , parsed => 1
});
assert_stats("foo.bam", {
    state => "fresh"
  , parsed_try => 1
  , parsed => 1
});
assert_stats("boats", { state => "uncreated" });

# module file - fixed
open my $fh, ">", "$testdir/module.bam" or die $!;
print $fh <<TEXT;
rule -- boats : foo.bam
rule boats -> //module/targets
TEXT
close $fh;

reconcile();
assert_stats(undef, {
    modules => 1
  , system_state_ok => 1
});
assert_stats(".", {
    reloaded => 2
});
assert_stats("module.bam", {
    parsed_try => 2
  , parsed => 2
});
assert_stats("foo.bam", {
    state => "fresh"
  , parsed_try => 1
  , parsed => 1
});
assert_stats("boats", { state => "uncreated" });

# build - creates the file
bam_build();
assert_stats("boats", {
    state => "fresh"
  , fsent_fresh => 1
});

# file was created by the foo formula
assert_file("$testdir/boats", "foo");
