/* A desc definition file generated by fab. fab is free software released under the
   GNU General Public License.

   As a special exception, desc definition files generated by fab (including this
   desc definition file) are excluded from the license covering fab itself, even if
   substantial portions of the fab source code are copied verbatim into the desc
   definition file. You may create a larger work that contains part or all of the build
   script and distribute that work under terms of your choice. */

#include "descriptor.h"
#include "build_slot/build_slot.h"
#include "build_slot.desc.h"
#include "macros.h"

struct descriptor_type API descriptor_fab_build_slot = {
  members_len : 12,
  members : (descriptor_field*[]) {
    &descriptor_fab_build_slot_pid,
    &descriptor_fab_build_slot_status,
    &descriptor_fab_build_slot_stage,
    &descriptor_fab_build_slot_path,
    &descriptor_fab_build_slot_pwd,
    &descriptor_fab_build_slot_args,
    &descriptor_fab_build_slot_envs,
    &descriptor_fab_build_slot_sources,
    &descriptor_fab_build_slot_targets,
    &descriptor_fab_build_slot_stdout_total,
    &descriptor_fab_build_slot_stderr_total,
    &descriptor_fab_build_slot_auxout_total,
  }
};

struct descriptor_field API descriptor_fab_build_slot_pid = { id : 1, code : 1
  , offset : offsetof(fab_build_slot, pid)
  , size : sizeof_member(fab_build_slot, pid)
};
struct descriptor_field API descriptor_fab_build_slot_status = { id : 2, code : 1
  , offset : offsetof(fab_build_slot, status)
  , size : sizeof_member(fab_build_slot, status)
};
struct descriptor_field API descriptor_fab_build_slot_stage = { id : 3, code : 2
  , offset : offsetof(fab_build_slot, stage)
  , size : sizeof_member(fab_build_slot, stage)
};
struct descriptor_field API descriptor_fab_build_slot_path = { id : 4, code : 3
  , offset : offsetof(fab_build_slot, path)
  , size : sizeof_member(fab_build_slot, path)
  , len_offset : offsetof(fab_build_slot, path_len)
};
struct descriptor_field API descriptor_fab_build_slot_pwd = { id : 5, code : 3
  , offset : offsetof(fab_build_slot, pwd)
  , size : sizeof_member(fab_build_slot, pwd)
  , len_offset : offsetof(fab_build_slot, pwd_len)
};
struct descriptor_field API descriptor_fab_build_slot_args = { id : 6, code : 4
  , offset : offsetof(fab_build_slot, args)
  , size : sizeof_member(fab_build_slot, args)
  , len_offset : offsetof(fab_build_slot, args_len)
};
struct descriptor_field API descriptor_fab_build_slot_envs = { id : 7, code : 4
  , offset : offsetof(fab_build_slot, envs)
  , size : sizeof_member(fab_build_slot, envs)
  , len_offset : offsetof(fab_build_slot, envs_len)
};
struct descriptor_field API descriptor_fab_build_slot_sources = { id : 8, code : 4
  , offset : offsetof(fab_build_slot, sources)
  , size : sizeof_member(fab_build_slot, sources)
  , len_offset : offsetof(fab_build_slot, sources_len)
};
struct descriptor_field API descriptor_fab_build_slot_targets = { id : 9, code : 4
  , offset : offsetof(fab_build_slot, targets)
  , size : sizeof_member(fab_build_slot, targets)
  , len_offset : offsetof(fab_build_slot, targets_len)
};
struct descriptor_field API descriptor_fab_build_slot_stdout_total = { id : 10, code : 2
  , offset : offsetof(fab_build_slot, stdout_total)
  , size : sizeof_member(fab_build_slot, stdout_total)
};
struct descriptor_field API descriptor_fab_build_slot_stderr_total = { id : 11, code : 2
  , offset : offsetof(fab_build_slot, stderr_total)
  , size : sizeof_member(fab_build_slot, stderr_total)
};
struct descriptor_field API descriptor_fab_build_slot_auxout_total = { id : 12, code : 2
  , offset : offsetof(fab_build_slot, auxout_total)
  , size : sizeof_member(fab_build_slot, auxout_total)
};
