/* A desc definition file generated by fab. fab is free software released under the
   GNU General Public License.

   As a special exception, desc definition files generated by fab (including this
   desc definition file) are excluded from the license covering fab itself, even if
   substantial portions of the fab source code are copied verbatim into the desc
   definition file. You may create a larger work that contains part or all of the build
   script and distribute that work under terms of your choice. */

#ifndef DESCRIPTOR_build_slot_H
#define DESCRIPTOR_build_slot_H

#include "descriptor.h"

extern struct descriptor_type descriptor_fab_build_slot;
extern struct descriptor_field descriptor_fab_build_slot_pid;
extern struct descriptor_field descriptor_fab_build_slot_status;
extern struct descriptor_field descriptor_fab_build_slot_stage;
extern struct descriptor_field descriptor_fab_build_slot_path;
extern struct descriptor_field descriptor_fab_build_slot_pwd;
extern struct descriptor_field descriptor_fab_build_slot_args;
extern struct descriptor_field descriptor_fab_build_slot_envs;
extern struct descriptor_field descriptor_fab_build_slot_sources;
extern struct descriptor_field descriptor_fab_build_slot_targets;
extern struct descriptor_field descriptor_fab_build_slot_stdout_total;
extern struct descriptor_field descriptor_fab_build_slot_stderr_total;
extern struct descriptor_field descriptor_fab_build_slot_auxout_total;

#endif
