#!/usr/bin/env perl
#
# Copyright (c) 2012-2015 Todd Freed <todd.freed@gmail.com>
#
# This file is part of fab.
#
# fab is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# fab is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with fab.  If not, see <http://www.gnu.org/licenses/>. */
#

use strict;
use warnings;
$SIG{__WARN__} = sub { die @_ };

die "cc not found" unless $ENV{cc};

my @cmd = (
    $ENV{cc}
  , split(/ /, $ENV{cflags})
  , (map { "-I$_" } split(/ /, $ENV{includes}))
  , $ENV{bm_source}
  , "-c"
  , "-o", $ENV{bm_target}
);

use Data::Dumper;
print(join(" ", @cmd) . "\n");

exec { $cmd[0] } @cmd

__DATA__

envs : {
  cc : {
    path-search : cc
  }

  deps : [
    select : [
      target
      traverse : {
        direction : down
        relation : strong
        max-distance : 1
      }
    ]

    property : relpath
  ]

  includes : [
    select : [
      module
      union : [
        # all directories in this module
        traverse : {
          direction : down
          min-distance : 0
          relation : fsmod
          nodes : dir
        }

        # imported directories
        traverse : {
          direction : down
          relation : imports
        }
      ]
    ]

    property : relpath
  ]
}
