#ifndef _PCRE_ERRTAB_H
#define _PCRE_ERRTAB_H
#include "xapi.h"
#define ETABLE_PCRE \
_E(-1, PCRE_ERROR_NOMATCH, "") \
_E(-2, PCRE_ERROR_NULL, "") \
_E(-3, PCRE_ERROR_BADOPTION, "") \
_E(-4, PCRE_ERROR_BADMAGIC, "") \
_E(-5, PCRE_ERROR_UNKNOWN_OPCODE, "") \
_E(-5, PCRE_ERROR_UNKNOWN_NODE, "") \
_E(-6, PCRE_ERROR_NOMEMORY, "") \
_E(-7, PCRE_ERROR_NOSUBSTRING, "") \
_E(-8, PCRE_ERROR_MATCHLIMIT, "") \
_E(-9, PCRE_ERROR_CALLOUT, "") \
_E(-12, PCRE_ERROR_PARTIAL, "") \
_E(-13, PCRE_ERROR_BADPARTIAL, "") \
_E(-14, PCRE_ERROR_INTERNAL, "") \
_E(-15, PCRE_ERROR_BADCOUNT, "") \
_E(-16, PCRE_ERROR_DFA_UITEM, "") \
_E(-17, PCRE_ERROR_DFA_UCOND, "") \
_E(-18, PCRE_ERROR_DFA_UMLIMIT, "") \
_E(-19, PCRE_ERROR_DFA_WSSIZE, "") \
_E(-20, PCRE_ERROR_DFA_RECURSE, "") \
_E(-21, PCRE_ERROR_RECURSIONLIMIT, "") \
_E(-22, PCRE_ERROR_NULLWSLIMIT, "") \
_E(-23, PCRE_ERROR_BADNEWLINE, "") \
_E(-24, PCRE_ERROR_BADOFFSET, "") \
_E(-26, PCRE_ERROR_RECURSELOOP, "") \
_E(-27, PCRE_ERROR_JIT_STACKLIMIT, "") \
_E(-28, PCRE_ERROR_BADMODE, "") \
_E(-29, PCRE_ERROR_BADENDIANNESS, "") \
_E(-30, PCRE_ERROR_DFA_BADRESTART, "") \
_E(-31, PCRE_ERROR_JIT_BADOPTION, "") \
_E(-32, PCRE_ERROR_BADLENGTH, "") \
_E(-33, PCRE_ERROR_UNSET, "") \

#if XAPI_STACKTRACE
#else
enum {
#define _E(a, b, c) PCRE_ ## b = a,
ETABLE_PCRE
#undef _E
};
#endif
#define ERRMIN_PCRE -33
#define ERRMAX_PCRE -1
extern errtab * perrtab_PCRE;
#endif
